export interface BorraImagg{
    cliente: string,
    puntos: string,
    producto: string,
    puntosG: string,
    efectivo: string,
    transferencia: string,
    vdRegalo: string,
    cheque: string,
    tdDebito: string,
    tdCredito: string,
    monto: string,
    money:string,
    moneyG:string,
  }